### ISSUE TITLE
[IOS] Image cache it : SDAnimatedImageView is not defined

### ISSUE THREAD

**Issue by kefahB** [triniwiz/nativescript-plugins#193]
```ts
Uncaught ReferenceError: SDAnimatedImageView is not defined
 at 
	createNativeView(file:///app/vendor.js:68193:28)
	at _setupUI(file:///app/vendor.js:30691:31)
	at (file:///app/vendor.js:30704:19)
	at eachChildView(file:///app/vendor.js:42250:28)
	at eachChild(file:///app/vendor.js:32948:14)
	at _setupUI(file:///app/vendor.js:30703:14)
	at (file:///app/vendor.js:30704:19)
	at eachChildView(file:///app/vendor.js:42250:28)
	at eachChild(file:///app/vendor.js:32948:14)
	at _setupUI(file:///app/vendor.js:30703:14)
	at (file:///app/vendor.js:30704:19)
	at eachChildView(file:///app/vendor.js:27696:13)
	at eachChild(file:///app/vendor.js:32948:14)
	at _setupUI(file:///app/vendor.js:30703:14)
	at (file:///app/vendor.js:30704:19)
	at eachChildView(file:///app/vendor.js:42250:28)
	at eachChild(file:///app/vendor.js:32948:14)
	at _setupUI(file:///app/vendor.js:30703:14)
	at (file:///app/vendor.js:30704:19)
	at eachChildView(file:///app/vendor.js:27696:13)
	at eachChildView(file:///app/vendor.js:45017:15)
	at eachChild(file:///app/vendor.js:32948:14)
	at _setupUI(file:///app/vendor.js:30703:14)
	at _addViewCore(file:///app/vendor.js:30550:18)
	at _addView(file:///app/vendor.js:30538:14)
	at UIViewControllerImpl.viewWillAppear(file:///app/vendor.js:44403:27)
', reason: '(null)'
*** First throw call stack:
(0x1addfe678 0x1a60a7c80 0x103e33d38 0x1038ecf50 0x1038eeb34 0x1038fefec 0x1038feba0 0x1add48f9c 0x1add45ca8 0x1add453f8 0x1f12fb4f8 0x1b016b8a0 0x1b016aedc 0x103e40044 0x103e3e710 0x103e25e4c 0x103df511c 0x103e2f740 0x10094027c 0x1d0aaedcc)
libc++abi: terminating due to uncaught exception of type NSException
```

**Comment by justinbeatz** [comment]
Is there any news about this issue, I also have the same error.

**Comment by kefahB** [comment]
Not yet, use nativescript-community/image instead it cache image by default

**Comment by nikoTM** [comment]
https://github.com/NativeScript/ios/commit/0d52056fdb102f40887abd47c9bc2af5f3cca94e

This solution provided by @triniwiz in the NativeScript discord worked for me as a temporary workaround (manually editing the python files locally) until it makes into the release.

**Comment by imperatormk** [comment]
@triniwiz Please make this happen!
