### ISSUE TITLE
Couchbase Android and nulls

### ISSUE THREAD

**Issue by jamescodesthings** [triniwiz/nativescript-plugins#40]
Hey, I don't have a great use case for this, but it's taken a while to understand why everything was doing the do on iOS and not Android. Hopefully it helps someone else.

The reason for null values in my object is I'm porting from a nasty old flat json file storage mechanism to a nice shiny couch-lite based system (thanks).

If my document contains a null value the createDocument method fails to save and returns null on `@triniwiz/nativescript-couchbase@1.2.1`.

e.g:
```js
const db = new CouchBase('somedb');
const id = db.createDocument({
  key: "val",
  someotherkey: null,
});
console.log(`returned id: ${id}`, id);
// the returned ID is null here, under the hood an exception is thrown (see below).
// No obvious cause from the logs until I added logging.
```

Relevant logs, ignore line numbers, had to add some logging to see what was happening.
```
03-12 17:03:47.342 20810 20810 E TNSCouchBase: Exception in fromJson
03-12 17:03:47.342 20810 20810 E TNSCouchBase: java.lang.IllegalArgumentException: Non-string or null key in data to be deserialized.
03-12 17:03:47.342 20810 20810 E TNSCouchBase: 	at com.couchbase.lite.Fleece.toCBLObject(Fleece.java:86)
03-12 17:03:47.342 20810 20810 E TNSCouchBase: 	at com.couchbase.lite.MutableDictionary.setValue(MutableDictionary.java:96)
03-12 17:03:47.342 20810 20810 E TNSCouchBase: 	at com.couchbase.lite.MutableDocument.setValue(MutableDocument.java:148)
03-12 17:03:47.342 20810 20810 E TNSCouchBase: 	at com.github.triniwiz.couchbase.Couchbase$Companion.serialize(Couchbase.kt:327)
03-12 17:03:47.342 20810 20810 E TNSCouchBase: 	at com.github.triniwiz.couchbase.Couchbase$Companion.fromJSON(Couchbase.kt:90)
03-12 17:03:47.342 20810 20810 E TNSCouchBase: 	at com.github.triniwiz.couchbase.Couchbase$Companion.saveFromJSON(Couchbase.kt:127)
03-12 17:03:47.342 20810 20810 E TNSCouchBase: 	at com.github.triniwiz.couchbase.Couchbase$Companion.saveFromJSON(Couchbase.kt:122)
03-12 17:03:47.342 20810 20810 E TNSCouchBase: 	at com.github.triniwiz.couchbase.Couchbase.saveFromJSON(Unknown Source:2)
03-12 17:03:47.342 20810 20810 E TNSCouchBase: 	at com.tns.Runtime.callJSMethodNative(Native Method)
03-12 17:03:47.342 20810 20810 E TNSCouchBase: 	at com.tns.Runtime.access$2200(Runtime.java:39)
03-12 17:03:47.342 20810 20810 E TNSCouchBase: 	at com.tns.Runtime$5.run(Runtime.java:1323)
03-12 17:03:47.342 20810 20810 E TNSCouchBase: 	at android.os.Handler.handleCallback(Handler.java:938)
03-12 17:03:47.342 20810 20810 E TNSCouchBase: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-12 17:03:47.342 20810 20810 E TNSCouchBase: 	at android.os.Looper.loop(Looper.java:223)
03-12 17:03:47.342 20810 20810 E TNSCouchBase: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
03-12 17:03:47.342 20810 20810 E TNSCouchBase: 	at java.lang.reflect.Method.invoke(Native Method)
03-12 17:03:47.342 20810 20810 E TNSCouchBase: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
03-12 17:03:47.342 20810 20810 E TNSCouchBase: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Might not be one to fix but is worth noting to save anyone else some time.

**Comment by triniwiz** [comment]
Thanks null should be saving
