### ISSUE TITLE
ImageZoom Crashing Android

### ISSUE THREAD

**Issue by keerl** [triniwiz/nativescript-plugins#44]
I am using ImageZoom in a NS8 + Angular project and I am getting this error right off the bat that is crashing my app. I tried cloning this repo and running the demos but I can't get them to build. Any idea what is causing this?

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateView failed
System.err: Error: java.lang.ExceptionInInitializerError
System.err:
System.err: StackTrace:
System.err: createNativeView(file: node_modules/@triniwiz/nativescript-image-zoom/index.android.js:9:0)
System.err:     at _setupUI(file: node_modules/@nativescript/core/ui/core/view-base/index.js:554:0)
System.err:     at (file: node_modules/@nativescript/core/ui/core/view-base/index.js:600:0)
System.err:     at eachChildView(file: node_modules/@nativescript/core/ui/layouts/layout-base-common.js:101:0)
System.err:     at eachChild(file: node_modules/@nativescript/core/ui/core/view/view-common.js:759:0)
System.err:     at _setupUI(file: node_modules/@nativescript/core/ui/core/view-base/index.js:599:0)
System.err:     at (file: node_modules/@nativescript/core/ui/core/view-base/index.js:600:0)
System.err:     at eachChildView(file: node_modules/@nativescript/core/ui/content-view/index.js:65:0)
System.err:     at eachChild(file: node_modules/@nativescript/core/ui/core/view/view-common.js:759:0)
System.err:     at _setupUI(file: node_modules/@nativescript/core/ui/core/view-base/index.js:599:0)
System.err:     at (file: node_modules/@nativescript/core/ui/core/view-base/index.js:600:0)
System.err:     at eachChildView(file: node_modules/@nativescript/core/ui/layouts/layout-base-common.js:101:0)
System.err:     at eachChild(file: node_modules/@nativescript/core/ui/core/view/view-common.js:759:0)
System.err:     at _setupUI(file: node_modules/@nativescript/core/ui/core/view-base/index.js:599:0)
System.err:     at (file: node_modules/@nativescript/core/ui/core/view-base/index.js:600:0)
System.err:     at eachChildView(file: node_modules/@nativescript/core/ui/content-view/index.js:65:0)
System.err:     at eachChildView(file: node_modules/@nativescript/core/ui/page/page-common.js:106:0)
System.err:     at eachChild(file: node_modules/@nativescript/core/ui/core/view/view-common.js:759:0)
System.err:     at _setupUI(file: node_modules/@nativescript/core/ui/core/view-base/index.js:599:0)
System.err:     at _addViewCore(file: node_modules/@nativescript/core/ui/core/view-base/index.js:450:0)
System.err:     at _addView(file: node_modules/@nativescript/core/ui/core/view-base/index.js:439:0)
System.err:     at onCreateView(file: node_modules/@nativescript/core/ui/frame/index.android.js:740:0)
System.err:     at onCreateView(file: node_modules/@nativescript/core/ui/frame/fragment.android.js:25:0)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1149)
System.err:     at com.tns.FragmentClass.onCreateView(FragmentClass.java:55)
System.err:     at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
System.err:     at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
System.err:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
System.err:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
System.err:     at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
System.err:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
System.err:     at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
System.err:     at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
System.err:     at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
System.err:     at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
System.err:     at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
System.err:     at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2641)
System.err:     at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
System.err:     at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2723)
System.err:     at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
System.err:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1200)
System.err:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
System.err:     at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
System.err:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
System.err:     at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
System.err:     at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
System.err:     at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
System.err:     at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
System.err:     at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
System.err:     at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2641)
System.err:     at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
System.err:     at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2723)
System.err:     at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
System.err:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1200)
System.err:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
System.err:     at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
System.err:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
System.err:     at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
System.err:     at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
System.err:     at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
System.err:     at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
System.err:     at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
System.err:     at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
System.err:     at android.os.Handler.handleCallback(Handler.java:938)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loop(Looper.java:223)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7656)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
System.err: Caused by: java.lang.ExceptionInInitializerError
System.err:     at okhttp3.internal.platform.Platform.get(Platform.java:85)
System.err:     at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263)
System.err:     at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229)
System.err:     at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1015)
System.err:     at com.squareup.picasso.OkHttp3Downloader.<init>(OkHttp3Downloader.java:71)
System.err:     at com.squareup.picasso.OkHttp3Downloader.<init>(OkHttp3Downloader.java:50)
System.err:     at com.squareup.picasso.OkHttp3Downloader.<init>(OkHttp3Downloader.java:40)
System.err:     at com.squareup.picasso.Picasso$Builder.build(Picasso.java:804)
System.err:     at com.squareup.picasso.provider.PicassoProvider.get(PicassoProvider.java:34)
System.err:     ... 52 more
System.err: Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 30
System.err:     at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:238)
System.err:     at okhttp3.internal.platform.Platform.findPlatform(Platform.java:202)
System.err:     at okhttp3.internal.platform.Platform.<clinit>(Platform.java:79)
System.err:     ... 61 more

```

**Comment by triniwiz** [comment]
It's coming from okhttp what plugins do you use ?

**Comment by triniwiz** [comment]
It's fixed in latest version

**Comment by mohammadrafigh** [comment]
@triniwiz The same exception throws for nativescript-socketio on Android 11.
