### ISSUE TITLE
nativescript-stripe Cannot build anymore

### ISSUE THREAD

**Issue by hirol888** [triniwiz/nativescript-plugins#64]
@nativescript/core 7.3.0, it was working fine and suddenly got this kind of errors.

I tried @triniwiz/nativescript-stripe 7.0.0-alpha3 to beta1, always got errors,

ERROR in ../node_modules/@triniwiz/nativescript-stripe/angular/index.ts
Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):
Error: /~~~~~~~~~~~~some path ~~~~~~~~~/node_modules/@triniwiz/nativescript-stripe/angular/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at NativeScriptAngularCompilerPlugin.getCompiledFile (/Users/huiningli/Documents/repos/Biz Core/CustomerPortalUI/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:951:23)
    at NativeScriptAngularCompilerPlugin.getCompiledFile (/Users/huiningli/Documents/repos/Biz Core/CustomerPortalUI/node_modules/@nativescript/webpack/plugins/NativeScriptAngularCompilerPlugin.js:29:26)
    at /Users/huiningli/Documents/repos/Biz Core/CustomerPortalUI/node_modules/@ngtools/webpack/src/loader.js:43:31
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

ERROR in ../node_modules/@triniwiz/nativescript-stripe/index.ts
Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):
Error: /~~~~some path ~~~~~~/node_modules/@triniwiz/nativescript-stripe/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at NativeScriptAngularCompilerPlugin.getCompiledFile (/Users/huiningli/Documents/repos/Biz Core/CustomerPortalUI/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:951:23)
    at NativeScriptAngularCompilerPlugin.getCompiledFile (/Users/huiningli/Documents/repos/Biz Core/CustomerPortalUI/node_modules/@nativescript/webpack/plugins/NativeScriptAngularCompilerPlugin.js:29:26)
    at /Users/huiningli/Documents/repos/Biz Core/CustomerPortalUI/node_modules/@ngtools/webpack/src/loader.js:43:31
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by triniwiz** [comment]
I'm seeing some ts source there also it's currently at beta-1

**Comment by hirol888** [comment]
I changed to beta-1, also run 'tns clean', 'npm cache verify', 'npm cache clean --force', but still got errors. It seems the issue is inside tsconfig.json?

**Comment by triniwiz** [comment]
Please update to the latest beta
