### ISSUE TITLE
Pod Install Error for Couchbase Plugin on M1 machine

### ISSUE THREAD

**Issue by razorsyntax** [triniwiz/nativescript-plugins#72]
Using M1 Mac and getting the following error when running `ns run ios`. 

When I uninstall the plugin, the app builds and loads without error.  I'm running this in a terminal using Rosetta.

```

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

` ` `
/opt/homebrew/lib/ruby/gems/2.7.0/bin/pod install
` ` `

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

` ` `
   CocoaPods : 1.10.1
        Ruby : ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [arm64-darwin20]
    RubyGems : 3.2.15
        Host : macOS 11.4 (20F71)
       Xcode : 12.5.1 (12E507)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /opt/homebrew/Cellar/ruby@2.7/2.7.3/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
` ` `

### Plugins

` ` `
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
` ` `

### Podfile

` ` `ruby
use_frameworks!

target "Sample" do
post_install do |installer|
  post_installNativeScript_CLI_Architecture_Exclusions_0 installer
end

# Begin Podfile - /Users/user/Documents/Dev/projec/Sample/platforms/ios/Podfile-exclusions
def post_installNativeScript_CLI_Architecture_Exclusions_0 (installer)
  installer.pods_project.build_configurations.each do |config|
    config.build_settings.delete "VALID_ARCHS"
    config.build_settings["EXCLUDED_ARCHS_x86_64"] = "arm64 arm64e"
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "i386 armv6 armv7 armv7s armv8 $(EXCLUDED_ARCHS_$(NATIVE_ARCH_64_BIT))"
    config.build_settings["EXCLUDED_ARCHS[sdk=iphoneos*]"] = "i386 armv6 armv7 armv7s armv8 x86_64"
  end
end
# End Podfile

# Begin Podfile - /Users/user/Documents/Dev/project/Sample/node_modules/@nativescript-community/drawingpad/platforms/ios/Podfile
pod 'SignatureView', :git => 'https://github.com/PeterStaev/SignatureView.git', :branch => 'svg-support'
# End Podfile

# NativeScriptPlatformSection /Users/user/Documents/Dev/project/Sample/node_modules/@triniwiz/nativescript-couchbase/platforms/ios/Podfile with 10.0
platform :ios, '10.0'
# End NativeScriptPlatformSection

# Begin Podfile - /Users/user/Documents/Dev/project/Sample/node_modules/@triniwiz/nativescript-couchbase/platforms/ios/Podfile
# platform :ios, '10.0'
use_frameworks!
pod 'CouchbaseLite', '~> 2.8.4'

# End Podfile
end
` ` `

### Error

` ` `
LoadError - dlopen(/opt/homebrew/lib/ruby/gems/2.7.0/gems/ffi-1.15.3/lib/ffi_c.bundle, 9): no suitable image found.  Did find:
	/opt/homebrew/lib/ruby/gems/2.7.0/gems/ffi-1.15.3/lib/ffi_c.bundle: mach-o, but wrong architecture
	/opt/homebrew/lib/ruby/gems/2.7.0/gems/ffi-1.15.3/lib/ffi_c.bundle: mach-o, but wrong architecture - /opt/homebrew/lib/ruby/gems/2.7.0/gems/ffi-1.15.3/lib/ffi_c.bundle
/opt/homebrew/Cellar/ruby@2.7/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/opt/homebrew/Cellar/ruby@2.7/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/ffi-1.15.3/lib/ffi.rb:5:in `rescue in <top (required)>'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/ffi-1.15.3/lib/ffi.rb:2:in `<top (required)>'
/opt/homebrew/Cellar/ruby@2.7/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/opt/homebrew/Cellar/ruby@2.7/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/ethon-0.14.0/lib/ethon.rb:3:in `<top (required)>'
/opt/homebrew/Cellar/ruby@2.7/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/opt/homebrew/Cellar/ruby@2.7/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/opt/homebrew/Cellar/ruby@2.7/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/opt/homebrew/Cellar/ruby@2.7/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:284:in `ensure_versions_file_loaded'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:208:in `search'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:165:in `search_for'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:267:in `each'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:267:in `sort_by'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:288:in `initial_state'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:210:in `start_resolution'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:168:in `resolve'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:94:in `resolve'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1074:in `block in resolve_dependencies'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/opt/homebrew/lib/ruby/gems/2.7.0/bin/pod:23:in `load'
/opt/homebrew/lib/ruby/gems/2.7.0/bin/pod:23:in `<main>'
` ` `

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

'pod install' command failed.
```

**Comment by InGuuuW** [comment]
I also encountered the same problem. Did you solve it?

**Comment by triniwiz** [comment]
Try w/o Rosetta
